version: "3.7"
services:
  app:
    build:
      args:
        user: admin
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: tradusquare
    container_name: tradusquare-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - tradusquare

  db:
    image: mysql:latest
    container_name: tradusquare-db
    restart: unless-stopped
    ports:
      - 33060:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - ./docker-compose/mysql/mysql-files:/var/lib/mysql-files
    networks:
      - tradusquare

  nginx:
    image: nginx:latest
    container_name: tradusquare-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - tradusquare

networks:
  tradusquare:
    driver: bridge
