name: LaravelDeploy

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development'
    steps:
      - name: Check the duplicate code in app directory
        run: php .vendor/bin/phpcpd app/ --min-lines=5 --min-tokens=10
