name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
   runs-on: ubuntu-latest
   if: github.ref == 'refs/heads/master'
   steps:

     - name: Deploy
       uses: AEnterprise/rsync-deploy@v1.0
       env:
         DEPLOY_KEY: ${{ secrets.KEY }}
         ARGS: '-avzh --exclude=".*"'
         SERVER_PORT: ${{ secrets.PORT }}
         FOLDER: "./"
         SERVER_IP: ${{ secrets.HOST }}
         USERNAME: ${{ secrets.USERNAME }}
         SERVER_DESTINATION: ${{ secrets.SERVER_DESTINATION }}
